version: '2'
services:
  consul:
    container_name: workshop-consul
    command: consul agent -dev -bind=0.0.0.0 -client=0.0.0.0
    image: consul:latest
    ports:
      - 8500:8500

  mysql:
    container_name: workshop-mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: test
      MYSQL_ROOT_HOST: '%'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1


