version: '2'
services:
  bff:
    container_name: bff
    image: workshop/bff:1
    environment:
        CONSUL_HOST: "ec2-54-179-179-235.ap-southeast-1.compute.amazonaws.com"
        JAVA_OPTS: "-Xmx256m -Xms256m"
        # APPDYNAMICS_CONTROLLER_HOST_NAME: "alan2017080114375031.saas.appdynamics.com"
        # APPDYNAMICS_CONTROLLER_PORT: "80"
        APPDYNAMICS_AGENT_APPLICATION_NAME: "workshop"
        APPDYNAMICS_AGENT_TIER_NAME: "test"
        APPDYNAMICS_AGENT_NODE_NAME: "bff"
    volumes:
        - ./agent:/agent
    ports:
        - 5678:5678
    networks:
        - workshop
    command: ["java", "-javaagent:/agent/javaagent.jar", "-jar", "app.jar"]

  product:
    container_name: product
    #command: consul agent -dev -bind=0.0.0.0 -client=0.0.0.0
    image: workshop/product:1
    environment:
        CONSUL_HOST: "ec2-54-179-179-235.ap-southeast-1.compute.amazonaws.com"
        JAVA_OPTS: "-Xmx256m -Xms256m"
        # APPDYNAMICS_CONTROLLER_HOST_NAME: "alan2017080114375031.saas.appdynamics.com"
        # APPDYNAMICS_CONTROLLER_PORT: "80"
        APPDYNAMICS_AGENT_APPLICATION_NAME: "workshop"
        APPDYNAMICS_AGENT_TIER_NAME: "test"
        APPDYNAMICS_AGENT_NODE_NAME: "product"
    volumes:
        - ./agent:/agent
    # ports:
    #     - 5678:8080
    networks:
        - workshop
    command: ["java", "-javaagent:/agent/javaagent.jar", "-jar", "app.jar"]

  order:
    container_name: order
    #command: consul agent -dev -bind=0.0.0.0 -client=0.0.0.0
    image: workshop/order:1
    environment:
        CONSUL_HOST: "ec2-54-179-179-235.ap-southeast-1.compute.amazonaws.com"
        JAVA_OPTS: "-Xmx256m -Xms256m"
        # APPDYNAMICS_CONTROLLER_HOST_NAME: "alan2017080114375031.saas.appdynamics.com"
        # APPDYNAMICS_CONTROLLER_PORT: "80"
        APPDYNAMICS_AGENT_APPLICATION_NAME: "workshop"
        APPDYNAMICS_AGENT_TIER_NAME: "test"
        APPDYNAMICS_AGENT_NODE_NAME: "order"
    volumes:
        - ./agent:/agent
    # ports:
    #     - 5678:8080
    networks:
        - workshop
    command: ["java", "-javaagent:/agent/javaagent.jar", "-jar", "app.jar"]

networks:
    workshop:
        driver: bridge
