server:
  port: 5678

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

logging:
  level:
    feign: DEBUG

spring:
  zipkin:
    base-url: http://${ZIPKIN_HOST:ec2-54-179-179-235.ap-southeast-1.compute.amazonaws.com}:9411